In [10]:
import pandas as pd

In [11]:
available_products_file_name = '../data/availableProducts.csv'
available_products_df = pd.read_csv(available_products_file_name, index_col='Product name')
available_products_df.head()

,Refrigerated,minimum package quantity,populatiry score,price,size score
Product name,,,,,
Pingui,True,4,10.0,2.0,2.0
Maxi King,True,3,1.0,2.0,4.0
Choco Fresh,True,5,1.0,2.0,2.0
Pingui Sachertorte,True,4,1.0,2.0,2.0
Paradiso,True,4,1.0,2.0,1.0

In [12]:
assignment_file_name = '../results/door_assignment_list.csv'
door_assignment_df = pd.read_csv(assignment_file_name)
door_assignment_df.head()

   Door Number   Item1        Item2      Item3  Refrigerated    Special Day
0            1  Pingui  Choco Fresh  Maxi King          True  first advent
1            2  Riegel   Schokobons        NaN         False            NaN
2            3   Bueno        Cards        NaN         False            NaN
3            4  Riegel   Schokobons        NaN         False            NaN
4            5  Riegel        Bueno        NaN         False            NaN

In [14]:
product_quantity_df = door_assignment_df[['Item1', 'Item2', 'Item3']].apply(pd.Series.value_counts)
product_quantity_df['Quantity'] = product_quantity_df.sum(axis=1)
product_quantity_df['Packaging quantity'] = available_products_df.loc[product_quantity_df.index, 'minimum package quantity']
product_quantity_df.drop([f'Item{index}' for index in range(1,3+1)], axis=1, inplace=True)
product_quantity_df["Bought"] = [True, True, False, True, False, False, False, False, False, False]
product_quantity_df

              Quantity  Packaging quantity  Bought
Bueno              6.0                   6    True
Cards              5.0                   5    True
Choco Fresh        5.0                   5   False
Happy Hippo        5.0                   5    True
Maxi King          3.0                   3   False
Nikolaus           1.0                   1   False
Pingui             4.0                   4   False
Riegel            10.0                  10   False
Schokobons         6.0                  20   False
Überraschung       3.0                   1   False